name: ci-mhs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-mhs-time:
    runs-on: ubuntu-latest
    steps:
    - name: checkout time repo
      uses: actions/checkout@v4
      with:
        path: time
    - name: checkout mhs repo
      uses: actions/checkout@v4
      with:
        repository: augustss/MicroHs
        ref: stable-2
        path: mhs
    - name: make and install mhs
      run: |
        cd mhs
        make minstall
    - name: compile and install time package
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        cd time
        mcabal install
    - name: run ShowDefaultTZAbbreviations test
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        cd time
        mhs test/ShowDefaultTZAbbreviations.hs -oShowDefaultTZAbbreviations
        ./ShowDefaultTZAbbreviations
    - name: run ShowTime test
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        cd time
        mhs test/ShowTime.hs -oShowTime
        ./ShowTime
    - name: cleanup
      run: |
        rm -rf $HOME/.mcabal
